kms:
  boto_resource_name: kms
  category: IAM and Security
  inventory_nodes:
    list_aliases:
      detail_param: ''
      item_key: ''
      item_search_id: ''
      permissions: ListAliases
      result_key: ''
    list_keys:
      detail_param: ''
      item_key: ''
      item_search_id: ''
      permissions: ListKeys
      result_key: ''
  region_type: local
secretsmanager:
  boto_resource_name: secretsmanager
  category: IAM and Security
  inventory_nodes:
    list_secrets:
      detail_param: ''
      item_key: ''
      item_search_id: ''
      permissions: ListSecrets
      result_key: ''
  region_type: local
